[package]
name = "compressed_string"
authors = ["Aztec Labs"]
compiler_version = ">=0.45.0"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/aztec-nr/aztec" }