services:
  ethereum:
    image: ghcr.io/foundry-rs/foundry@sha256:29ba6e34379e79c342ec02d437beb7929c9e254261e8032b17e187be71a2609f
    command: >
      '
      [ -n "$$FORK_URL" ] && ARGS="$$ARGS --fork-url $$FORK_URL";
      [ -n "$$FORK_BLOCK_NUMBER" ] && ARGS="$$ARGS --fork-block-number $$FORK_BLOCK_NUMBER";
      echo anvil -p $$ANVIL_PORT --host 0.0.0.0 --chain-id 31337 --silent $$ARGS;
      anvil -p $$ANVIL_PORT --host 0.0.0.0 --chain-id 31337 --silent $$ARGS
      '
    ports:
      - "${ANVIL_PORT:-8545}:${ANVIL_PORT:-8545}"
    environment:
      FORK_URL:
      FORK_BLOCK_NUMBER:
      ANVIL_PORT: ${ANVIL_PORT:-8545}

  aztec:
    image: "aztecprotocol/aztec:0.57.0"
    ports:
      - "${PXE_PORT:-8080}:${PXE_PORT:-8080}"
    environment:
      LOG_LEVEL: verbose
      DEBUG: aztec:simulator:client_execution_context, aztec:sandbox, aztec:avm_simulator:debug_log
      HOST_WORKDIR: "${PWD}" # Loaded from the user shell to show log files absolute path in host
      ETHEREUM_HOST: ${ETHEREUM_HOST:-http://ethereum:${ANVIL_PORT:-8545}}
      L1_CHAIN_ID: 31337
      ARCHIVER_POLLING_INTERVAL_MS: 50
      P2P_BLOCK_CHECK_INTERVAL_MS: 50
      SEQ_TX_POLLING_INTERVAL_MS: 50
      WS_BLOCK_CHECK_INTERVAL_MS: 50
      PXE_BLOCK_POLLING_INTERVAL_MS: 50
      ARCHIVER_VIEM_POLLING_INTERVAL_MS: 500
      PXE_PORT: ${PXE_PORT:-8080}
      PORT: ${AZTEC_NODE_PORT:-8080}
      TEST_ACCOUNTS: ${TEST_ACCOUNTS:-true}
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
    depends_on:
      - ethereum
    command: "start --sandbox"
  pxe_1:
    environment:
      LOG_LEVEL: verbose
      DEBUG: aztec:simulator:client_execution_context, aztec:sandbox, aztec:avm_simulator:debug_log
    image: "aztecprotocol/aztec:0.57.0"
    ports:
      - "${PXE_PORT:-8081}:${PXE_PORT:-8081}"
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log_pxe_1:rw
    depends_on:
      - aztec
    command: "start --pxe --port 8081 --pxe.nodeUrl=http://aztec:8080/"
    restart: always
  pxe_2:
    environment:
      LOG_LEVEL: verbose
      DEBUG: aztec:simulator:client_execution_context, aztec:sandbox, aztec:avm_simulator:debug_log
    image: "aztecprotocol/aztec:0.57.0"
    ports:
      - "${PXE_PORT:-8082}:${PXE_PORT:-8082}"
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log_pxe_2:rw
    depends_on:
      - aztec
    command: "start --pxe --port 8082 --pxe.nodeUrl=http://aztec:8080/"
    restart: always
  pxe_3:
    environment:
      LOG_LEVEL: verbose
      DEBUG: aztec:simulator:client_execution_context, aztec:sandbox, aztec:avm_simulator:debug_log
    image: "aztecprotocol/aztec:0.57.0"
    ports:
      - "${PXE_PORT:-8083}:${PXE_PORT:-8083}"
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log_pxe_3:rw
    depends_on:
      - aztec
    command: "start --pxe --port 8083 --pxe.nodeUrl=http://aztec:8080/"
    restart: always