services:
  txe:
    image: "aztecprotocol/aztec:0.67.0"
    environment:
      DEBUG: # Loaded from the user shell if explicitly set
      LOG_LEVEL: # Loaded from the user shell if explicitly set
      HOST_WORKDIR: "${PWD}" # Loaded from the user shell to show log files absolute path in host
    volumes:
      - ./log:/usr/src/yarn-project/aztec/log:rw
      - ${HOME}:${HOME}
    command: start --txe --port 8081

  aztec-nargo:
    image: "aztecprotocol/aztec-nargo:0.66.0"
    environment:
      HOME: # Loaded from the user shell
      NARGO_FOREIGN_CALL_TIMEOUT: "300000" # To avoid timeouts when many tests run at once
    working_dir: "${PWD}/contracts/z_imburse_registry"
    command: "test --silence-warnings --oracle-resolver http://txe:8081 --package z_imburse_registry"
    volumes:
      - ${HOME}:${HOME}
    depends_on:
      - txe