[package]
name = "z_imburse_registry"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=1.0.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.0", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.0", directory="noir-projects/noir-contracts/contracts/token_contract" }
address_note = { path = "../address_note" }
compressed_string = { path = "../compressed_string" }
date_parser = { path = "../../circuits/date_parser"}
generators = { path = "../generators" }
uint_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.67.0", directory = "noir-projects/aztec-nr/uint-note" }
zimburse_verifiers = { path = "../../circuits/zimburse_verifiers" }
z_imburse_escrow = { path = "../z_imburse_escrow" }
zkemail = { path = '../../../zkemail.nr/lib' }