[package]
name = "z_imburse_note_contract"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.1", directory="noir-projects/aztec-nr/aztec" }
compressed_string = { path = "../compressed_string" }