
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type UnencryptedL2Log,
  type Wallet,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import ZImburseContractRegistryContractArtifactJson from './ZImburseContractRegistry.json' assert { type: 'json' };
//@ts-ignore
export const ZImburseContractRegistryContractArtifact = loadContractArtifact(ZImburseContractRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ZImburseContractRegistry;
 */
export class ZImburseContractRegistryContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, ZImburseContractRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, ZImburseContractRegistryContract.artifact, wallet) as Promise<ZImburseContractRegistryContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, contract_class_id: FieldLike) {
    return new DeployMethod<ZImburseContractRegistryContract>(Fr.ZERO, wallet, ZImburseContractRegistryContractArtifact, ZImburseContractRegistryContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, contract_class_id: FieldLike) {
    return new DeployMethod<ZImburseContractRegistryContract>(publicKeysHash, wallet, ZImburseContractRegistryContractArtifact, ZImburseContractRegistryContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ZImburseContractRegistryContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<ZImburseContractRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<ZImburseContractRegistryContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      ZImburseContractRegistryContractArtifact,
      ZImburseContractRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ZImburseContractRegistryContractArtifact;
  }
  

  public static get storage(): ContractStorageLayout<'escrow_contract_id' | 'managed_escrows' | 'participants' | 'participant_escrows' | 'contract_registration'> {
      return {
        escrow_contract_id: {
      slot: new Fr(1n),
    },
managed_escrows: {
      slot: new Fr(2n),
    },
participants: {
      slot: new Fr(3n),
    },
participant_escrows: {
      slot: new Fr(4n),
    },
contract_registration: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'escrow_contract_id' | 'managed_escrows' | 'participants' | 'participant_escrows' | 'contract_registration'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'ParticipantNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(2232136525),
        },
ParticipantNote: {
          id: new NoteSelector(3017618054),
        }
    } as ContractNotes<'AddressNote' | 'ParticipantNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** check_and_register_participant(participant: struct, participant_name: string, admin: struct, escrow: struct) */
    check_and_register_participant: ((participant: AztecAddressLike, participant_name: string, admin: AztecAddressLike, escrow: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(contract_class_id: field) */
    constructor: ((contract_class_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_contract_registration_status(escrow_contract: struct) */
    get_contract_registration_status: ((escrow_contract: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow_class_id() */
    get_escrow_class_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_managed_escrows(admin: struct, page_index: integer) */
    get_managed_escrows: ((admin: AztecAddressLike, page_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participant_escrows(participant: struct, page_index: integer) */
    get_participant_escrows: ((participant: AztecAddressLike, page_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participants(escrow: struct, page_index: integer) */
    get_participants: ((escrow: AztecAddressLike, page_index: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_escrow(escrow_contract: struct) */
    register_escrow: ((escrow_contract: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_participant(participant: struct, participant_name: string, admin: struct, escrow: struct) */
    register_participant: ((participant: AztecAddressLike, participant_name: string, admin: AztecAddressLike, escrow: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
