[package]
name = "z_imburse_escrow"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.66.0", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.66.0", directory="noir-projects/noir-contracts/contracts/token_contract" }
address_note = { path = "../address_note" }
compressed_string = { path = "../compressed_string" }
generators = { path = "../generators" }
zimburse_verifiers = { path = "../../circuits/zimburse_verifiers" }
zkemail = { path = '../../../zkemail.nr/lib' }