[package]
name = "z_imburse_escrow"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/aztec" }
address_note = { path = "../address_note" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/compressed-string" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/noir-contracts/contracts/token_contract" }
zimburse_verifiers = { path = "../../circuits/zimburse_verifiers" }
