[package]
name = "generators"
authors = ["Mach-34"]
compiler_version = ">=1.0.0"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.0", directory="noir-projects/aztec-nr/aztec" }