[package]
name = "zimburse_contract_registry"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/aztec" }
address_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/address-note" }
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages", tag="aztec-packages-v0.56.0", directory="noir-projects/noir-protocol-circuits/crates/types" }
zimburse_escrow = { path = "../zimburse_escrow" }