[package]
name = "linode_email_verifier"
type = "lib"
authors = ["Mach-34"]
compiler_version = ">=0.34.0"

[dependencies]
zkemail = { tag = "v0.2.0", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }