[package]
name = "linode_email_verifier"
type = "lib"
authors = ["Mach-34"]
compiler_version = ">=0.35.0"

[dependencies]
zkemail = { tag = "v0.3.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
date_parser = { path = "../date_parser"}