[package]
name = "zimburse_verifiers"
type = "lib"
authors = ["Mach-34"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/aztec-nr/aztec" }
zkemail = { tag = "v0.3.3", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
date_parser = { path = "../date_parser"}
