[package]
name = "z_imburse_escrow_registry"
type = "contract"
authors = ["Mach-34"]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/aztec" }
compressed_string = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.56.0", directory="noir-projects/aztec-nr/compressed-string" }
address_note = { path = "../address_note" }
z_imburse_escrow = { path = "../z_imburse_escrow" }
z_imburse_dkim_registry = { path = "../z_imburse_dkim_registry" }