[package]
name = "address_note"
authors = ["aztec-labs"]
compiler_version = ">=0.35.0"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.67.1", directory="noir-projects/aztec-nr/aztec" }