[package]
name = "united_email_verifier"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
zkemail = { tag = "v0.4.0", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
zimburse_verifiers = { path = "../../zimburse_verifiers" }